user_service_host = "http://userservice:8000/"
user_service_base_endpoint = user_service_host + "user/"
user_service_login_endpoint = user_service_base_endpoint + "login/"
user_service_logout_endpoint = user_service_base_endpoint + "logout/"
user_service_signin_endpoint = user_service_base_endpoint + "signin/"

ether_host = "http://etherservice:8001/"
ether_accounts_base_endpoint = ether_host + "accounts/"
ether_accounts_add_endpoint = ether_accounts_base_endpoint + "add/"
ether_accounts_remove_endpoint = ether_accounts_base_endpoint + "remove/"
ether_accounts_at_endpoint = ether_accounts_base_endpoint + "at/"
ether_accounts_connect_to_clef_endpoint = ether_accounts_base_endpoint + "connect_to_clef/"
ether_accounts_disconnect_from_clef_endpoint = ether_accounts_base_endpoint + "disconnect_from_clef/"
ether_accounts_from_mnemonic_endpoint = ether_accounts_base_endpoint + "from_mnemonic/"
ether_accounts_load_endpoint = ether_accounts_base_endpoint + "load/"
ether_accounts_clear_endpoint = ether_accounts_base_endpoint + "clear/"

ether_erc20_base_endpoint = ether_host + "erc20/"
ether_erc20_name_endpoint = ether_erc20_base_endpoint + "name/"
ether_erc20_symbol_endpoint = ether_erc20_base_endpoint + "symbol/"
ether_erc20_decimals_endpoint = ether_erc20_base_endpoint + "decimals/"
ether_erc20_total_supply_endpoint = ether_erc20_base_endpoint + "total_supply/"
ether_erc20_balance_of_endpoint = ether_erc20_base_endpoint + "balance_of/"
ether_erc20_transfer_endpoint = ether_erc20_base_endpoint + "transfer/"
ether_erc20_transfer_from_endpoint = ether_erc20_base_endpoint + "transfer_from/"
ether_erc20_approve_endpoint = ether_erc20_base_endpoint + "approve/"
ether_erc20_allowance_endpoint = ether_erc20_base_endpoint + "allowance/"
