version: "3.9"

services:

  botservice:
    image: bot_service:1.0
    container_name: bot-service
    build: ./bot_service
    command: gunicorn bot_service.wsgi:application --bind 0.0.0.0:8002
    env_file: .env.dev
    ports:
      - "8002:8002"
    networks:
      - main

  etherservice:
    image: ether_service:1.0
    container_name: ether-service
    build: ./ether_service
    depends_on:
      - botservice
    command: gunicorn ether_service.wsgi:application --bind 0.0.0.0:8001
    env_file: .env.dev
    ports:
      - "8001:8001"
    networks:
      - main

  userservice:
    image: user_service:1.0
    container_name: user-service
    build: ./user_service
    depends_on:
      - botservice
    command: gunicorn user_service_project.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.dev
    ports:
      - "8000:8000"
    networks:
      - main

networks:
  main: