version: "3.9"

services:

  botservice:
    image: bot_service:1.0
    container_name: bot-service
    build:
      context: ./bot_service
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: gunicorn bot_service.wsgi:application --bind 0.0.0.0:8002
    env_file: .env.test
    ports:
      - "8002:8002"
    networks:
      - main

  etherservice:
    image: ether_service:1.0
    container_name: ether-service
    build:
      context: ./ether_service
      dockerfile: Dockerfile
    depends_on:
      - botservice
      - redis
    command: gunicorn ether_service.wsgi:application --bind 0.0.0.0:8001
    env_file: .env.test
    ports:
      - "8001:8001"
    networks:
      - main

  userservice:
    image: user_service:1.0
    container_name: user-service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    depends_on:
      - botservice
      - redis
    command: gunicorn user_service_project.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.test
    ports:
      - "8000:8000"
    networks:
      - main

  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - main

networks:
  main: